repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length=100"]
  - repo: local
    hooks:
      - id: verify-deps
        name: Verify Python dependencies
        entry: python scripts/verify_deps.py
        language: system
        types: [python]
